# Generated by Django 6.0.6 on 2026-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_backgrounds/"
            ),
        ),
    ]
